### DISCUSSION TITLE
[Terminator][Subapp]

### DISCUSSION THREAD

**Discussion by coskrrb2002** [idaholab/moose#21546] [Q&A General] [answered]
Hi moose users,

Recently, I am using a Terminator.C to finish my subapp in a multiapp.

However, if I use the Terminator.C, my subapp does not calculate anything after the first timestep of my mainapp.

It seems like the Terminator.C turn off the subapp for whole timesteps for mainapp after the subapp reached the criteria.

I checked this issue with put the following print line in the execute class of Terminator.C:

std::cout << "Time Execute Terminator Test :" << _t << std::endl;

Here I attached the output results during the calculation:

```
--------------------------------------------------------------------
sub_app0: Time Step 41, time = 41, dt = 1
sub_app0:
sub_app0: Performing automatic scaling calculation
sub_app0:
sub_app0:  0 Nonlinear |R| = 0.000000e+00
sub_app0:  Solve Converged!
currents: 29.6614 Older currents:92.9853
changed potential difference: 1e-07
**Time Execute Terminator Test :41**
sub_app0:
sub_app0: Postprocessor Values:
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0: | time           | EcorrPostCal   | Isum           | SideAverageO2  | SideAverageTTT |
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0: :                :                :                :                :                :
sub_app0: |   2.700000e+01 |  -2.918000e-01 |  -2.135603e+04 |   2.500000e-01 |  -2.919000e-01 |
sub_app0: |   2.800000e+01 |  -2.918100e-01 |   1.029218e+04 |   2.500000e-01 |  -2.918000e-01 |
sub_app0: |   2.900000e+01 |  -2.918200e-01 |   7.123863e+03 |   2.500000e-01 |  -2.918100e-01 |
sub_app0: |   3.000000e+01 |  -2.918300e-01 |   3.956327e+03 |   2.500000e-01 |  -2.918200e-01 |
sub_app0: |   3.100000e+01 |  -2.918400e-01 |   7.895681e+02 |   2.500000e-01 |  -2.918300e-01 |
sub_app0: |   3.200000e+01 |  -2.918300e-01 |  -2.376415e+03 |   2.500000e-01 |  -2.918400e-01 |
sub_app0: |   3.300000e+01 |  -2.918310e-01 |   7.895681e+02 |   2.500000e-01 |  -2.918300e-01 |
sub_app0: |   3.400000e+01 |  -2.918320e-01 |   4.729349e+02 |   2.500000e-01 |  -2.918310e-01 |
sub_app0: |   3.500000e+01 |  -2.918330e-01 |   1.563094e+02 |   2.500000e-01 |  -2.918320e-01 |
sub_app0: |   3.600000e+01 |  -2.918320e-01 |  -1.603082e+02 |   2.500000e-01 |  -2.918330e-01 |
sub_app0: |   3.700000e+01 |  -2.918321e-01 |   1.563094e+02 |   2.500000e-01 |  -2.918320e-01 |
sub_app0: |   3.800000e+01 |  -2.918322e-01 |   1.246473e+02 |   2.500000e-01 |  -2.918321e-01 |
sub_app0: |   3.900000e+01 |  -2.918323e-01 |   9.298528e+01 |   2.500000e-01 |  -2.918322e-01 |
sub_app0: |   4.000000e+01 |  -2.918324e-01 |   6.132331e+01 |   2.500000e-01 |  -2.918323e-01 |
sub_app0: |   4.100000e+01 |  -2.918325e-01 |   2.966143e+01 |   2.500000e-01 |  -2.918324e-01 |
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0:
sub_app0:
sub_app0: Time Step 42, time = 42, dt = 1
sub_app0:
sub_app0: Performing automatic scaling calculation
sub_app0:
sub_app0:  0 Nonlinear |R| = 0.000000e+00
sub_app0:  Solve Converged!
currents: -2.00038 Older currents:61.3233
changed potential difference: 1e-07
**Time Execute Terminator Test :42**
Time :42
sub_app0:
sub_app0: Postprocessor Values:
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0: | time           | EcorrPostCal   | Isum           | SideAverageO2  | SideAverageTTT |
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0: :                :                :                :                :                :
sub_app0: |   2.800000e+01 |  -2.918100e-01 |   1.029218e+04 |   2.500000e-01 |  -2.918000e-01 |
sub_app0: |   2.900000e+01 |  -2.918200e-01 |   7.123863e+03 |   2.500000e-01 |  -2.918100e-01 |
sub_app0: |   3.000000e+01 |  -2.918300e-01 |   3.956327e+03 |   2.500000e-01 |  -2.918200e-01 |
sub_app0: |   3.100000e+01 |  -2.918400e-01 |   7.895681e+02 |   2.500000e-01 |  -2.918300e-01 |
sub_app0: |   3.200000e+01 |  -2.918300e-01 |  -2.376415e+03 |   2.500000e-01 |  -2.918400e-01 |
sub_app0: |   3.300000e+01 |  -2.918310e-01 |   7.895681e+02 |   2.500000e-01 |  -2.918300e-01 |
sub_app0: |   3.400000e+01 |  -2.918320e-01 |   4.729349e+02 |   2.500000e-01 |  -2.918310e-01 |
sub_app0: |   3.500000e+01 |  -2.918330e-01 |   1.563094e+02 |   2.500000e-01 |  -2.918320e-01 |
sub_app0: |   3.600000e+01 |  -2.918320e-01 |  -1.603082e+02 |   2.500000e-01 |  -2.918330e-01 |
sub_app0: |   3.700000e+01 |  -2.918321e-01 |   1.563094e+02 |   2.500000e-01 |  -2.918320e-01 |
sub_app0: |   3.800000e+01 |  -2.918322e-01 |   1.246473e+02 |   2.500000e-01 |  -2.918321e-01 |
sub_app0: |   3.900000e+01 |  -2.918323e-01 |   9.298528e+01 |   2.500000e-01 |  -2.918322e-01 |
sub_app0: |   4.000000e+01 |  -2.918324e-01 |   6.132331e+01 |   2.500000e-01 |  -2.918323e-01 |
sub_app0: |   4.100000e+01 |  -2.918325e-01 |   2.966143e+01 |   2.500000e-01 |  -2.918324e-01 |
sub_app0: |   4.200000e+01 |  -2.918325e-01 |  -2.000378e+00 |   2.500000e-01 |  -2.918325e-01 |
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0:
CopyTransfer: TTT
CopyTransfer: TTT

Performing automatic scaling calculation

 0 Nonlinear |R| = 8.472638e-02
      0 Linear |R| = 3.680385e+00
      1 Linear |R| = 1.804670e-15
 1 Nonlinear |R| = 8.309315e-02
      0 Linear |R| = 3.588376e+00
      1 Linear |R| = 7.778159e-15
 2 Nonlinear |R| = 2.241028e-03
 Solve Converged!

Outlier Variable Residual Norms:
  HS-: 2.241028e-03

Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
| time           | Ecorr          | FClm           | FCu2p          | FCuCl2m        | FHSm           | FO2            | IA             | IC             | ID             | IE             | IS             | O2             |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e-09 |  -2.918325e-01 |  -6.539886e+00 |   0.000000e+00 |   3.269943e+00 |  -2.214755e+09 |  -8.978969e-01 |   3.155004e+05 |  -3.465343e+05 |   0.000000e+00 |   2.961443e-07 |   2.136907e+14 |   2.499999e-01 |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+


Time Step 2, time = 2.1e-09, dt = 1.1e-09
CopyTransfer: O2
CopyTransfer: O2
sub_app0:
sub_app0: Time Step 0, time = 0
sub_app0:
sub_app0: Postprocessor Values:
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0: | time           | EcorrPostCal   | Isum           | SideAverageO2  | SideAverageTTT |
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0: |   0.000000e+00 |  -2.918325e-01 |  -2.000378e+00 |   2.500000e-01 |  -2.918325e-01 |
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0:
CopyTransfer: TTT
CopyTransfer: TTT

Performing automatic scaling calculation

 0 Nonlinear |R| = 2.465074e-03

      0 Linear |R| = 8.524832e-04
      1 Linear |R| = 1.886083e-19
 1 Nonlinear |R| = 6.162670e-04
      0 Linear |R| = 3.013980e-04
      1 Linear |R| = 3.515695e-19
 2 Nonlinear |R| = 1.540669e-04
 Solve Converged!

Outlier Variable Residual Norms:
  HS-: 1.540669e-04

Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
| time           | Ecorr          | FClm           | FCu2p          | FCuCl2m        | FHSm           | FO2            | IA             | IC             | ID             | IE             | IS             | O2             |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e-09 |  -2.918325e-01 |  -6.539886e+00 |   0.000000e+00 |   3.269943e+00 |  -2.214755e+09 |  -8.978969e-01 |   3.155004e+05 |  -3.465343e+05 |   0.000000e+00 |   2.961443e-07 |   2.136907e+14 |   2.499999e-01 |
|   2.100000e-09 |  -2.918325e-01 |  -6.535205e+00 |   0.000000e+00 |   3.267602e+00 |  -1.384216e+08 |  -8.978960e-01 |   3.152746e+05 |  -3.465340e+05 |   0.000000e+00 |   7.403611e-08 |   1.335560e+13 |   2.499998e-01 |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+


Time Step 3, time = 3.31e-09, dt = 1.21e-09
CopyTransfer: O2
CopyTransfer: O2
sub_app0:
sub_app0: Time Step 0, time = 0
sub_app0:
sub_app0: Postprocessor Values:
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0: | time           | EcorrPostCal   | Isum           | SideAverageO2  | SideAverageTTT |
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0: |   0.000000e+00 |  -2.918325e-01 |  -2.000378e+00 |   2.500000e-01 |  -2.918325e-01 |
sub_app0: +----------------+----------------+----------------+----------------+----------------+
sub_app0:
CopyTransfer: TTT
CopyTransfer: TTT

------------------------------------------------------------------------------------------------
```
So, as you can see in the above results. The Terminator does not participate in the subapp calculation after the first timestep of mainapp.

Is it a bug?

Kind regards,
Nakkyu
