### DISCUSSION TITLE
Unable to Install Moose Framework Due to Package Conflicts

### DISCUSSION THREAD

**Discussion by BouncedGodzilla** [idaholab/moose#27253] [Q&A General] [answered]
### Bug Description

I have a MacBook Pro, 15 in., 2017 make, running on OSX Ventura 13.6.3. It seems that I am unable to update my OSX any further, as my make is no longer supported by Apple. For a class, I am supposed to install MOOSE. I have followed the instructions on the MOOSE website:

https://mooseframework.inl.gov/getting_started/installation/conda.html 

to install MOOSE. Previously I had tried to install the prebuilt model. After setting up mini forge and conda, I run the command:

**conda create -n moose moose-dev=2024.03.15**

which will inevitably run into the error:

**UnsatisfiableError: The following specifications were found to be incompatible with each other:**

which then lists a long list of packages which are supposedly incompatible and with an ending copula saying:

**The following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.16=0
  - feature:|@/osx-64::__osx==10.16=0

Your installed version is: 10.16**

I have tried installing MOOSE many times and this error is consistently encountered. My terminal shell is -zsh, but I previously tried with bash. I have reinstalled miniforge, tried other troubleshooting suggestions from the MOOSE website, mainly related to testing environment stuff. If I try to uninstall MOOSE, it says that there is no such environment on my computer, which means MOOSE has never been installed. Is MOOSE not compatible with Ventura 13.6.3 any longer? Is there likely something on my computer blocking its installation? Is there a known workaround for this issue?

Thank you.

### Steps to Reproduce

Follow instructions for installing miniforge, conda, and then MOOSE on my computer, a 2017 make MacBook Pro 15 in. running OSX Ventura 13.6.3. from the website:

**https://mooseframework.inl.gov/getting_started/installation/conda.html**

### Impact

I am unable to install MOOSE at all. I need it for my university course homework. I can workout an alternative way to use it by borrowing somebody's computer to do this homework, but such would be cumbersome to have to do.

**Comment by milljm** [comment]
I need to change this to a discussion, as it is not a bug in MOOSE (no amount of changes we make in MOOSE will alter your results).

**Comment by milljm** [comment]
Firstly, we have build/test machines that are still operating among this architecture (Intel Macs), so the installation procedures should still be valid for your hardware.

I'd like to understand the environment you are operating in. Its most likely there are multiple Conda installations, or perhaps a second third-party package manager (like Homebrew), which may be interfering with the installation process.

Can you run the following tool, and report the results:
```bash
cd moose/scripts
./diagnostics.sh
```
Should give us a better picture as to your running environment.

**Reply by milljm** [reply]
To be clear, our packages will work as far back as MacOS 10.15 (Catalina), for Intel based Macs.

Our Conda build target specs:
```yaml
#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX10.15.sdk                                    # [not arm64 and osx]
  - /opt/MacOSX11.3.sdk                                     # [arm64]

macos_min_version:                                          # [osx]
  - 10.15                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]
```
