### DISCUSSION TITLE
Is it possible to install two different versions of MOOSE on one system (Linux)?

### DISCUSSION THREAD

**Discussion by keassyguang** [idaholab/moose#30436] [Q&A Getting Started]
### Check these boxes if you have followed the posting rules.

- [X] I have consulted the [Posting Guidelines](https://github.com/idaholab/moose/discussions/18270).
- [X] I have searched the [Discussions Forum](https://github.com/idaholab/moose/discussions) and [MOOSE Framework Troubleshooting](https://mooseframework.inl.gov/help/troubleshooting.html) and have not found what I was looking for
- [X] Q&A Getting Started is the most appropriate category for my question (trouble installing, beginner user, ...)

### Issue or question about MOOSE

Hi moose developers,

I want to install an older version of MOOSE together with the latest version on my Linux machine. The latest version has already been installed successfully. Do we have any instructions on how to install an older version of MOOSE in the case of the newest one is already installed? Let's say I found a release here https://github.com/idaholab/moose/releases/tag/2024-11-11-release. I have downloaded the zip file, what do I do next?

The reason could be something similar to https://github.com/idaholab/moose/discussions/29611. Some code I developed last year can be run at that time, but not with the latest version.

Many thanks.

**Comment by GiudGiud** [comment]
Hello

Certainly. You can use git workspaces or simply use another folder for having the source code


Then for libmesh and the other packages, they live in a conda environnement. You will want to create a new environment then select the version of moose-dev that corresponds to the moose commit you want to use.

There is a script in moose/scripts, the versioner.PY that can help you find those commits

**Reply by keassyguang** [reply]
Thank you very much. There are so many commits, and they seem to be arranged randomly when I listed them by using command something like
```
git log --since="2024-12-21" --until="2024-12-31" --pretty=format:"%h %ad %s" --date=short
```
at least not by date. How do I know which commit matches a specific moose-dev version? Any good way to show the commits and their corresponding moose-dev? preferably list them based on date

**Reply by GiudGiud** [reply]
you can also use this file [scripts/tests/versioner_hashes.yaml](https://github.com/idaholab/moose/blob/next/scripts/tests/versioner_hashes.yaml) to see the matches between moose-dev and moose / dependencies versions

**Reply by keassyguang** [reply]
Thank you very much.

From the [versioner_hashes.yaml](https://github.com/idaholab/moose/blob/next/scripts/tests/versioner_hashes.yaml), I can find something like this:
```
a29438b9ccb11dc2dddf2b9b0a5d5c0bbaf96472: #29624
  tools:
    hash: 5abb5f2
  mpi:
    hash: 82bbd28
  petsc:
    hash: e78a9a4
  libmesh:
    hash: b8b3d69
  wasp:
    hash: e97f1e3
  moose-dev:
    hash: 5b49120
9da58ad93351b19cb23d850361f00ab98db3330b: #29900
  libmesh:
    full_version: 2024.12.02_1
    hash: b8b3d69
  libmesh-vtk:
    full_version: 9.3.0_5
    hash: 9a4dbab
  moose-dev:
    full_version: 2025.02.18
    hash: 5b49120
  mpi:
    full_version: 2024.12.23
    hash: 82bbd28
  peacock:
    full_version: 2024.12.23
    hash: ef44cb6
  petsc:
    full_version: 3.22.1.193.g72c1e49ee3d_1
    hash: e78a9a4
  pprof:
    full_version: 2024.12.23_0
    hash: fe051bc
  seacas:
    full_version: 2024.08.15_2
    hash: 2dd352c
  tools:
    full_version: 2024.12.23
    hash: 5abb5f2
  wasp:
    full_version: 2025.01.07_0
    hash: e97f1e3
```
However, there is no moose-dev number of the first commit. Only the hash is provided. The moose-dev number of the second one is `moose-dev=2025.02.18`.
And by using the command `conda search moose-dev --channel idaholab`, I can find the available moose-dev (part of the full list)
```
moose-dev                 2024.11.15           mpich  public              
moose-dev                 2024.11.15         openmpi  public              
moose-dev                 2024.12.02           mpich  public              
moose-dev                 2024.12.02         openmpi  public              
moose-dev                 2024.12.23           mpich  public              
moose-dev                 2024.12.23         openmpi  public              
moose-dev                 2025.02.18           mpich  public              
moose-dev                 2025.02.18         openmpi  public              
moose-dev                 2025.02.27           mpich  public              
moose-dev                 2025.02.27         openmpi  public              
moose-dev                 2025.03.03           mpich  public              
moose-dev                 2025.03.03         openmpi  public              
moose-dev                 2025.03.06           mpich  public              
moose-dev                 2025.03.06         openmpi  public              
moose-dev                 2025.03.24           mpich  public              
moose-dev                 2025.03.24         openmpi  public              
moose-dev                 2025.04.02           mpich  public              
moose-dev                 2025.04.02         openmpi  public              
moose-dev                 2025.04.11           mpich  public              
moose-dev                 2025.04.11         openmpi  public              
moose-dev                 2025.04.22           mpich  public              
moose-dev                 2025.04.22         openmpi  public 
```
Since ‘moose-dev 2024.12.23 mpich public’ is ahead of ‘moose-dev 2025.02.18 mpich public’, so the first commit corresponding to the to the moose-dev should be ‘moose-dev=2024.12.23’, right? 

If every thing is correct, then I will do the following steps
**Check commit**
```
cd ~/projects/moose_old
git clone https://github.com/idaholab/moose.git
cd moose
git checkout a29438b9ccb11dc2dddf2b9b0a5d5c0bbaf96472
```
**Create a new conda environment**
```
conda create -n moose-old moose-dev=2024.12.23=mpich
conda activate moose-old
```
**Build** 
```
cd ~/projects/moose_old/YourAppName
make -j 6
./run_tests -j 6
```
Is there anything wrong with these steps?
