### ISSUE TITLE
THM documentation is missing template arguments

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#20797]
## Bug Description
Various pages in THM documentation make use of template parameters, such as the name of the project, executable, etc. While the `config.yml` for the module itself has these arguments specified:
```
    MooseDocs.extensions.template:
        active: True
        args:
            project-name: Thermal Hydraulics Module
            project-name-abbrev: THM
            bin-opt: thermal_hydraulics-opt
            bin-dbg: thermal_hydraulics-dbg
```
the `config.yml` for the combined documentation does not, and thus the documentation on the MOOSE website is flawed.

## Steps to Reproduce
Look at https://mooseframework.inl.gov/modules/thermal_hydraulics/tutorials/basics/execution.html, for example.

## Impact
THM documentation is confusing for users, as there are words missing in various places.
