### ISSUE TITLE
'versioner.py' leading to build errors on public apps

### ISSUE THREAD

**Issue by TheGreatCid** [idaholab/moose#28809]
### Bug Description

I've noticed that the following lines in `versioner.py` are causing CI documentation builds to fail in public apps

```
def get_yamlcontents(self, commit):
        """ load yaml file contents at time of supplied commit """
        # Load the yaml file at the given commit; the location changed
        # from module_hash.yaml -> versioner.yaml at changed_commit
        changed_commit = '2bd844dc5d4de47238eab94a3a718e9714592de1'
        if self.git_ancestor(changed_commit, commit) and commit != changed_commit:
            _file = 'versioner.yaml'
        else:
            _file = 'module_hash.yaml'
        yaml_file = os.path.abspath(os.path.join(MOOSE_DIR, "scripts", _file))
 ``` 
 
 I've noted this in RACCOON and Zapdos
 
 This is the error seen,
 
 ```
 Submodule 'large_media' (https://github.com/idaholab/large_media) registered for path 'large_media'
Cloning into '/home/runner/work/zapdos/zapdos/moose/large_media'...
Submodule path 'large_media': checked out '19f9bb9a092270d4a317db0c6d21a7a495af1e27'
MooseDocs.build (MainProcess): Loading configuration files
fatal: Not a valid commit name 2bd844dc5d4de47238eab94a3a718e9714592de1
Traceback (most recent call last):
  File "/home/runner/work/zapdos/zapdos/doc/./moosedocs.py", line 29, in <module>
    sys.exit(main.run())
```

The issue began with MOOSE commit `a166589` when `versioner.py` was added to `load_config.py`(as well as other files for setting up python tests)

### Steps to Reproduce

Running a build test on a public app causes the error. 
Here is an example `.yml` from RACCOON

```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: moose
          condarc: |
            channels:
              - conda-forge
              - https://conda.software.inl.gov/public
          init-shell: bash
          create-args: >-
            moose-dev
            lcov

      - name: Compile RACCOON (without coverage)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash -el {0}
        run: |
          make -j 2

      - name: Build documentation 
        shell: bash -el {0}
        run: |
          mkdir gh-pages
          cd doc
          ./moosedocs.py check
          ./moosedocs.py build --destination ../gh-pages/ # ERROR OCCURS HERE
```

### Impact

Prevents passing documentation tests in public app CI pipelines.
